<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="Protos\users_service.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentMigrator" Version="7.1.0" />
        <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
        <PackageReference Include="FluentMigrator.Runner.Postgres" Version="7.1.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.64.0" />
        <PackageReference Include="linq2db" Version="5.4.1.9" />
        <PackageReference Include="Npgsql" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rates.Domain\Rates.Domain.csproj" />
      <ProjectReference Include="..\Rates.Migration.Shared\Rates.Migration.Shared.csproj" />
      <ProjectReference Include="..\Rates.Shared\Rates.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="key">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="key.pub.pem">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
